package com.basinwatch.learning;

import java.util.List;

public final class LearningCatalog {
    private static final List<ArchitectureCard> CARDS = List.of(
            new ArchitectureCard("Observation intake",
                    "Keep rainfall and level reports flowing while the operator uses the console.",
                    "Thread, Runnable, piped character streams, buffered reader",
                    "engine/SensorFeed.java · engine/SensorIntake.java",
                    "A feed owns its timed lifecycle; intake is a separate task connected by a character pipe.",
                    "Doing a blocking read on Swing's event thread would freeze map selection and dispatch."),
            new ArchitectureCard("Waiting work",
                    "Queue observations until one of the response processors can examine them.",
                    "Producer/consumer, monitor, wait(), notifyAll()",
                    "engine/EventBuffer.java",
                    "A bounded queue waits in a condition loop and signals after state changes.",
                    "Workers would spin while idle, or a full queue could grow without a safety limit."),
            new ArchitectureCard("Finite response stock",
                    "Assign each pump, crew, truck, or evacuation vehicle to at most one active job.",
                    "Synchronization, critical section, shared state",
                    "domain/ResourceAllocator.java · domain/BasinModel.java",
                    "Check and decrement every required resource in one short atomic reservation.",
                    "Two dispatches could otherwise both see the same final crew as available."),
            new ArchitectureCard("Sensor history",
                    "Retain typed rainfall and water-rise measurements beyond the current run.",
                    "DataOutputStream, BufferedOutputStream, FileOutputStream",
                    "io/SensorArchive.java · engine/ArchiveWorker.java",
                    "Write fields in a versioned typed order through a buffered binary file stream.",
                    "A restart would lose the evidence needed to review the simulated event sequence."),
            new ArchitectureCard("Operator audit and reports",
                    "Keep readable operational decisions and export a reviewable situation report.",
                    "Writer, BufferedWriter, FileWriter-equivalent character I/O",
                    "io/OperationalJournal.java · io/ReportWriter.java",
                    "Write explicit UTF-8 text separately from typed sensor bytes.",
                    "A binary sensor file alone is not a practical human-readable audit trail."),
            new ArchitectureCard("Recoverable sessions",
                    "Restore flood levels, equipment availability, active jobs, and recent events.",
                    "Serialization, deserialization, transient/runtime separation",
                    "io/SnapshotStore.java · io/SessionSnapshot.java",
                    "Serialize a versioned DTO, validate a round-trip, then atomically replace the save.",
                    "The next launch would start over; serializing live locks or threads would not restore a valid runtime."),
            new ArchitectureCard("File catalogue",
                    "List saved scenarios and show operators where the local evidence is stored.",
                    "File paths and metadata",
                    "io/AppPaths.java · io/SaveCatalog.java",
                    "Use filesystem metadata for presence, names, and sizes; use streams for contents.",
                    "The interface could not distinguish an absent save from a readable save."),
            new ArchitectureCard("Independent response processing",
                    "Handle incoming observations without blocking observation production or the UI.",
                    "Thread lifecycle, Runnable, start(), interrupt(), join()",
                    "engine/BasinEngine.java · engine/SensorFeed.java",
                    "Keep tasks separate from execution threads and stop owned work cooperatively.",
                    "One slow event or disk write could freeze the user-facing control path."),
            new ArchitectureCard("Resource deadlock prevention",
                    "Avoid a cycle in which two jobs hold different units and wait forever for each other.",
                    "Monitor ownership, lock ordering, deadlock",
                    "domain/ResourceAllocator.java · ARCHITECTURE.md",
                    "Use one brief inventory monitor and perform no I/O or waiting while holding it.",
                    "Cross-acquiring multiple resource locks can create circular wait and stall dispatch."),
            new ArchitectureCard("Scheduling experiment",
                    "Let an engineer observe how background archive scheduling hints affect a busy run.",
                    "Thread priority",
                    "engine/ArchiveWorker.java · Systems Inspector",
                    "Lower priority is optional and best-effort; application severity and correctness use explicit data.",
                    "Treating priority as a guarantee could delay urgent work or make behavior JVM-dependent."),
            new ArchitectureCard("Typed observations and missions",
                    "Give each event and operation only the data and behavior appropriate to its role.",
                    "Encapsulation, composition, interfaces, polymorphism, enums",
                    "domain/BasinEvent.java · domain/MissionType.java · domain/BasinModel.java",
                    "Use immutable event values, bounded enums, and aggregates rather than public mutable records.",
                    "Unvalidated strings and exposed inventory would make invalid state much easier to create."),
            new ArchitectureCard("Visible failure boundaries",
                    "Keep a corrupt reading, unavailable resource, or unwritable file from becoming a silent success.",
                    "Checked/runtime exceptions and input validation",
                    "engine/SensorIntake.java · io/SnapshotStore.java · app/MainFrame.java",
                    "Validate at the boundary and report failures with an operational context.",
                    "Operators could mistake missing or corrupt information for a healthy basin."));

    private LearningCatalog() {
    }

    public static List<ArchitectureCard> cards() {
        return CARDS;
    }
}
